name: Deployment automation

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout Code
        uses : actions/checkout@v4

      - name : Deploy via SSh
        uses : appleboy/ssh-action@v1.0.3
        with :
          host : ${{ secrets.SSH_HOST }}
          username : ${{ secrets.SSH_USERNAME }}
          key : ${{ secrets.SSH_PRIVATE_KEY }}
          script : |
            cd /home/rootuser/git-actions
            git pull
            docker compose up -d --build 